// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace gtest2html.Page.Css.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\gtest2html\dev\dev\dotnet\libgtest2html\Page\Css\Template\CssTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CssTemplate : CssTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("body {\r\n\tfont-family: \'Roboto\', sans-serif;\r\n\tline-height: 1.5;\r\n\tmargin: 0;\r\n\tpa" +
                    "dding: 0;\r\n\tbackground-color: #FEFEFE; /* Slightly grayish white */\r\n\tcolor: rgb" +
                    "a(0, 0, 0, 0.85);\r\n}\r\n\r\nh1 {\r\n\ttext-align: center;\r\n\tcolor: rgba(0, 0, 0, 0.85);" +
                    "\r\n\tmargin-top: 24px;\r\n\tfont-size: 52px;\r\n\tfont-weight: 600;\r\n}\r\n\r\nh2 {\r\n\ttext-al" +
                    "ign: left; /* Align text to the left */\r\n\tmargin: 20px; /* Set margin to 24px */" +
                    "\r\n\tfont-size: 32px; /* Smaller than h1 */\r\n}\r\n\r\na {\r\n    margin: 8px 24px;\r\n}\r\n\r" +
                    "\ntable {\r\n\twidth: auto;\r\n\tborder-collapse: collapse;\r\n\tmargin: 8px 32px;\r\n\tbackg" +
                    "round-color: #fff;\r\n\tborder: 3px solid #FEFEFE; /* Add border to table */\r\n\tbord" +
                    "er-radius: 0px;\r\n\toverflow: hidden;\r\n\tmargin-left: 32px; /* Indent tables to app" +
                    "ear nested under h2 */\r\n}\r\n\r\ntable a {\r\n\tcolor: blue; /* Style for links inside " +
                    "tables */\r\n\ttext-decoration: underline;\r\n    margin: 8px 0px;\r\n}\r\n\r\nth {\r\n\tbackg" +
                    "round-color: lightblue; /* Skyblue column headers */\r\n\tcolor: rgba(0, 0, 0, 0.85" +
                    ");\r\n\tfont-weight: 600;\r\n\tpadding: 4px 8px;\r\n\ttext-align: center;\r\n\tborder: 2px s" +
                    "olid #FEFEFE; /* Add border to table */\r\n    min-width: 80px;\r\n}\r\n\r\ntd {\r\n\tpaddi" +
                    "ng: 4px 32px;\r\n\ttext-align: center;\r\n\tborder: 2px solid #FEFEFE; /* Add border t" +
                    "o table */\r\n    border-radius: 0px; /* Rounded corners for cells */\r\n}\r\n\r\ntr {\r\n" +
                    "\tbackground-color: #f0f0f0;\r\n}\r\n\r\ntr:hover {\r\n\tbackground-color: #FEFEFE;\r\n}\r\n\r\n" +
                    "caption {\r\n\tfont-weight: 500;\r\n\tmargin-bottom: 12px;\r\n\tfont-size: 16px;\r\n\tcolor:" +
                    " rgba(0, 0, 0, 0.85);\r\n}\r\n\r\n.name {\r\n    width: auto;\r\n\tpadding: 4px 48px;\r\n\ttex" +
                    "t-align: left;\r\n}\r\n\r\n.status {\r\n\tpadding: 4px 48px 4px 8px;\r\n\ttext-align: left;\r" +
                    "\n}\r\n\r\n.test {\r\n\twidth: auto;\r\n\tpadding: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.fai" +
                    "lures {\r\n\twidth: auto;\r\n\tpadding: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.disables " +
                    "{\r\n\twidth: auto;\r\n\tpadding: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.errors {\r\n\twidt" +
                    "h: auto;\r\n\tpadding: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.time {\r\n\twidth: auto;\r\n" +
                    "\tpadding: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.timestamp {\r\n\twidth: auto;\r\n\tpadd" +
                    "ing: 4px 48px;\r\n\ttext-align: left;\r\n}\r\n\r\n.passed {\r\n\tcolor: limegreen; /* Text c" +
                    "olor */\r\n\tfont-weight: bold; /* Bold text */\r\n}\r\n\r\n.not_passed {\r\n\tbackground-co" +
                    "lor: red; /* Cell background color */\r\n\tcolor: white; /* Text color */\r\n\tfont-we" +
                    "ight: bold; /* Bold text */\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CssTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
