// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace gtest2html.Page.Html.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TestMessageHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestMessageHtmlTemplate : HtmlTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<html>
	<head>
		<meta charset=""utf-8""/>
		<meta http-equiv=""X-UA-Compatible"" content=""IE=EDGE,chrome=1"" />
		<title>Error report</title>
		<link rel=""stylesheet"" type=""text/css"" href=""report.css"" />
	</head>
	<body>
		<div>
			<h1>Test report - Error message</h1>
		</div>
		<div>
			<a href=""index.html"">Back</a>
		</div>
		<div>
			<table>
				<caption>Message</caption>
				<tbody>
					<tr>
						<th>Error message</th>
					</tr>
					<tr>
						<td>");
            
            #line 30 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TestMessageHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_failure.Message));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</tbody>\r\n\t\t\t</table>\r\n\t\t\t</table>\r\n\t\t</div>\r\n\t</body>\r\n</" +
                    "html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
