// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace gtest2html.Page.Html.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TopIndexHtmlTemplate : HtmlTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<!DOCTYPE html>
<html>
	<head>
		<meta charset=""utf-8""/>
		<meta http-equiv=""X-UA-Compatible"" content=""IE=EDGE,chrome=1"" />
		<title>Test report - overview and content</title>
		<link rel=""stylesheet"" type=""text/css"" href=""report.css"" />
	</head>
	<body>
		<div>
			<h1>Test report</h1>
		</div>
		<div>
			<table>
				<caption>Summary</caption>
				<tbody>
					<tr>
						<th>Tests</th>
						<th>Failures</th>
						<th>Disables</th>
						<th>Errors</th>
						<th>Time</th>
					</tr>
					<tr>
						<td class=""tests"">");
            
            #line 32 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestNum));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"failures\">");
            
            #line 33 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FailureNum));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"disables\">");
            
            #line 34 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DisableNum));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"errors\">");
            
            #line 35 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ErrorNum));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"time\">");
            
            #line 36 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TimeNum));
            
            #line default
            #line hidden
            this.Write(@"</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div>
			<table>
				<caption>Test suites</caption>
				<tbody>
					<tr>
						<th>Name</th>
						<th>Tests</th>
						<th>Failure</th>
						<th>Disables</th>
						<th>Errors</th>
						<th>Time</th>
						<th>Timestamp
					</tr>
					");
            
            #line 54 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
 foreach (var testSuiteItem in _testSuitesCollection) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td class=\"name\"><a href=\"");
            
            #line 57 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.HtmlFileName));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 57 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.TestName));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"tests\">");
            
            #line 58 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.Tests));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"failures\">");
            
            #line 59 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.Failures));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"disables\">");
            
            #line 60 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.Disabled));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"errors\">");
            
            #line 61 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.Errors));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"time\">");
            
            #line 62 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.Time));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"timestamp\">");
            
            #line 63 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuiteItem.TimeStamp));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t\r\n\t\t\t\t\t");
            
            #line 66 "E:\development\gtest2html\dev\dev\libgtest2html\Page\Html\Template\TopIndexHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</tbody>\r\n\t\t\t</table>\r\n\t\t</div>\r\n\t</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
