// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace gtest2html.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using gtest2html;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestSuitesHtmlTemplate : TemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<html>\r\n\t<head>\r\n\t\t<meta charset=\"utf-8\"/>\r\n\t\t<meta http-equiv=\"X-UA-Compatible\" " +
                    "content=\"IE=EDGE,chrome=1\" />\r\n\t\t<title>Test report");
            
            #line 13 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestSuites.Name));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"report.css\" />\r\n\t</head>" +
                    "\r\n\t<body>\r\n\t\t<div>\r\n\t\t\t<h1>Test report - detail</h1>\r\n\t\t</div>\r\n\t\t<div>\r\n\t\t\t<a h" +
                    "ref=\"index.html\">TOP</a>\r\n\t\t</div>\r\n\t\t<div>\r\n\t\t");
            
            #line 24 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 foreach (var testSuite in TestSuites.TestItems) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<table>\r\n\t\t\t\t<caption>");
            
            #line 26 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuite.Name));
            
            #line default
            #line hidden
            this.Write("</caption>\r\n\t\t\t\t<tbody>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<th>test name</th>\r\n\t\t\t\t\t\t<th>State</th" +
                    ">\r\n\t\t\t\t\t\t<th>Result</th>\r\n\t\t\t\t\t\t<th>Judge</th>\r\n\t\t\t\t\t\t<th>Timestamp</th>\r\n\t\t\t\t\t\t" +
                    "<th>Time</th>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t");
            
            #line 36 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 foreach (var testCase in testSuite.TestCases) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td class=\"name\">");
            
            #line 38 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"status\">");
            
            #line 39 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Status));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"result\">");
            
            #line 40 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Result));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t");
            
            #line 41 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 if (0 == string.Compare(testCase.Judge, "NG")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<td class=\"not_passed\"><a href=\"");
            
            #line 42 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testSuite.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 42 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Name));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 42 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Judge));
            
            #line default
            #line hidden
            this.Write("</a></td>\r\n\t\t\t\t\t\t");
            
            #line 43 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<td class=\"passed\">");
            
            #line 44 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Judge));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t");
            
            #line 45 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<td class=\"time\">");
            
            #line 46 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Timestamp));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t<td class=\"timestamp\">");
            
            #line 47 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(testCase.Time));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t\t");
            
            #line 49 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</tbody>\r\n\t\t\t</table>\r\n\t\t");
            
            #line 52 "E:\development\gtest2html\dev\dev\gtest2html\Template\TestSuitesHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</div>\r\n\t</body>\r\n</html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
